version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3010:3000"  # Host port 3001 maps to container port 3000
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=nutonium_db
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    command: ./wait-for-mysql.sh mysql npm run dev

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nutonium_db
      MYSQL_USER: nutonium_user
      MYSQL_PASSWORD: nutonium_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
